# 既存Picoのconfig.pyはそのまま使用します。このファイルは自動転送されません。
WIFI_SSID = 'YOUR_WIFI_SSID'
WIFI_PASSWORD = 'YOUR_WIFI_PASSWORD'
DISCORD_WEBHOOK_URL = 'YOUR_DISCORD_WEBHOOK_URL'

# Botモード（設定するとWebhookの代わりに同じ投稿を更新）
BOT_TOKEN = 'YOUR_BOT_TOKEN'
BOT_CHANNEL_ID = 'YOUR_CHANNEL_ID'
BOT_APPLICATION_ID = 'YOUR_APPLICATION_ID'
